"""empty message

Revision ID: 189ab5d92c3d
Revises: 8d4a7f4637b5
Create Date: 2021-03-30 19:14:22.180749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189ab5d92c3d'
down_revision = '8d4a7f4637b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('birth', sa.String(length=250), nullable=False))
    op.add_column('character', sa.Column('hair', sa.String(length=250), nullable=False))
    op.add_column('character', sa.Column('height', sa.String(length=250), nullable=False))
    op.add_column('character', sa.Column('mass', sa.String(length=250), nullable=False))
    op.add_column('character', sa.Column('skin', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'character', ['hair'])
    op.create_unique_constraint(None, 'character', ['skin'])
    op.create_unique_constraint(None, 'character', ['birth'])
    op.create_unique_constraint(None, 'character', ['height'])
    op.create_unique_constraint(None, 'character', ['mass'])
    op.add_column('planets', sa.Column('climate', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('diameter', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('gravity', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('orbital_period', sa.String(length=250), nullable=False))
    op.add_column('planets', sa.Column('rotation_period', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'rotation_period')
    op.drop_column('planets', 'orbital_period')
    op.drop_column('planets', 'gravity')
    op.drop_column('planets', 'diameter')
    op.drop_column('planets', 'climate')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_constraint(None, 'character', type_='unique')
    op.drop_column('character', 'skin')
    op.drop_column('character', 'mass')
    op.drop_column('character', 'height')
    op.drop_column('character', 'hair')
    op.drop_column('character', 'birth')
    # ### end Alembic commands ###
